### ISSUE TITLE
Doubt in configuring the app

### ISSUE THREAD

**Issue by codes-and-stories** [IOrlandoni/lock-issues#5]
How to configure the app to lock issues soon after they're opened?

**Comment by thisisnacho** [comment]
You could lock issues when they are opened with the following workflow.

#### Sample file: `.github/workflows/lock-opened-issues.yml`
    name: Lock opened issue

    on: 
      issues:
        types: [opened]

    jobs:
      lock:
        runs-on: ubuntu-latest
        steps:
        - uses: OSDKDev/lock-issues@v1.1
          with:
            repo-token: "${{ secrets.GITHUB_TOKEN }}"

**Comment by codes-and-stories** [comment]
@Dunning-Kruger 

     Thank you!
